export const FreelancersDummy = [
  {
    name: 'James Anderson',
    role: 'Frontend Developer',
    rate: '$15/hr',
    jobSuccess: '100% Job Success',
    projects: '50+ projects',
    location: 'India',
    rating: 5,
  },
  {
    name: 'Emily Clark',
    role: 'Backend Developer',
    rate: '$150/hr',
    jobSuccess: '98% Job Success',
    projects: '150+ projects',
    location: '',
    rating: 5,
  },
  {
    name: 'Daniel Williams',
    role: 'Python Developer',
    rate: '$60/hr',
    jobSuccess: '100% Job Success',
    projects: '100+ projects',
    location: '',
    rating: 4,
  },
  {
    name: 'Olivia Johnson',
    role: 'Java Developer',
    rate: '$150/hr',
    jobSuccess: '100% Job Success',
    projects: '60+ projects',
    location: '',
    rating: 4.5,
  },
  {
    name: 'Michael Harris',
    role: 'React Developer',
    rate: '$100/hr',
    jobSuccess: '93% Job Success',
    projects: '50+ projects',
    location: '',
    rating: 3.5,
  },
  {
    name: 'James Anderson',
    role: 'Frontend Developer',
    rate: '$15/hr',
    jobSuccess: '100% Job Success',
    projects: '50+ projects',
    location: 'India',
    rating: 4.5,
  },  {
    name: 'James Anderson',
    role: 'Frontend Developer',
    rate: '$15/hr',
    jobSuccess: '100% Job Success',
    projects: '50+ projects',
    location: 'India',
    rating: 5,
  },  {
    name: 'James Anderson',
    role: 'Frontend Developer',
    rate: '$15/hr',
    jobSuccess: '100% Job Success',
    projects: '50+ projects',
    location: 'India',
    rating: 5,
  },  {
    name: 'James Anderson',
    role: 'Frontend Developer',
    rate: '$15/hr',
    jobSuccess: '100% Job Success',
    projects: '50+ projects',
    location: 'India',
    rating: 5,
  },  {
    name: 'James Anderson',
    role: 'Frontend Developer',
    rate: '$15/hr',
    jobSuccess: '100% Job Success',
    projects: '50+ projects',
    location: 'India',
    rating: 5,
  },  {
    name: 'James Anderson',
    role: 'Frontend Developer',
    rate: '$15/hr',
    jobSuccess: '100% Job Success',
    projects: '50+ projects',
    location: 'India',
    rating: 5,
  },  {
    name: 'James Anderson',
    role: 'Frontend Developer',
    rate: '$15/hr',
    jobSuccess: '100% Job Success',
    projects: '50+ projects',
    location: 'India',
    rating: 5,
  },  {
    name: 'James Anderson',
    role: 'Frontend Developer',
    rate: '$15/hr',
    jobSuccess: '100% Job Success',
    projects: '50+ projects',
    location: 'India',
    rating: 5,
  },
];