export const projects = [
    // Your project data here
    {
      title: "E-Commerce Website",
      description:
        "Need an experienced Full Stack Developer to build a custom e-commerce website.",
      category: "Web Development",
      bids: 0,
      price: "750 USD",
      rating: 4,
      timePosted: "37 seconds ago",
    },
    {
      title: "Website Development Using WordPress",
      description: "Looking for an experienced WordPress Developer.",
      category: "Web Development",
      bids: 0,
      price: "250 USD",
      rating: 3,
      timePosted: "59 seconds ago",
    },
    {
      title: "Data Entry in Microsoft Word",
      description: "Looking for an experienced person who can type fast.",
      category: "Typing",
      bids: 0,
      price: "50 USD",
      rating: 2,
      timePosted: "1 minute ago",
    },
    {
      title: "Python Developer",
      description: "Need an experienced Python Developer.",
      category: "Software Development",
      bids: 10,
      price: "100 USD per hour",
      rating: 5,
      timePosted: "10 minutes ago",
    },
    {
      title: "C++ Developer",
      description:
        "I want a C++ Developer who has a strong foundation in data structures.",
      category: "Software Development",
      bids: 45,
      price: "75 USD per hour",
      rating: 4,
      timePosted: "27 minutes ago",
    },
    {
      title: "Machine Learning Using Python",
      description:
        "Need an experienced Python Developer who has a strong foundation in ML/AI.",
      category: "Software Development",
      bids: 90,
      price: "175 USD per hour",
      rating: 5,
      timePosted: "59 minutes ago",
    },
    {
      title: "Figma Designer",
      description: "I want a Figma designer who can design responsive websites.",
      category: "Web Design",
      bids: 120,
      price: "600 USD",
      rating: 4,
      timePosted: "1 hour ago",
    },
    {
      title: "React Developer",
      description: "Looking for an experienced React developer.",
      category: "Software Development",
      bids: 300,
      price: "200 USD",
      rating: 3,
      timePosted: "3 hours ago",
    },
    {
      title: "Backend Developer",
      description: "Need an experienced Backend Developer to build websites.",
      category: "Software Development",
      bids: 500,
      price: "800 USD",
      rating: 4,
      timePosted: "5 hours ago",
    },
    {
      title: "PHP Developer",
      description: "Looking for an experienced PHP Developer to build games.",
      category: "Software Development",
      bids: 600,
      price: "800 USD",
      rating: 4,
      timePosted: "6 hours ago",
    },
  ];
  